version: 2
log-file: "/Users/Oli/.local/state/nvim/efm.log"
log-level: 1
root-markers:
  - .git/
  - package.json

tools:
  eslint: &eslint
    lint-command: "eslint_d -f unix --stdin"
    lint-ignore-exit-code: true
    lint-stdin: true

  fish: &fish
    format-command: "fish_indent"
    to-stdin: true

  prettier: &prettier
    format-command: "prettier"

  python-black: &python-black
    format-command: "black --no-color -q -"
    format-stdin: true

  stylua: &stylua
    format-command: "stylua --color Never -"
    format-stdin: true
    root-markers:
      - stylua.toml

languages:
  css:
    - <<: *prettier
  fish:
    - <<: *fish
  html:
    - <<: *prettier
  javascript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  json:
    - <<: *prettier
  lua:
    - <<: *stylua
  markdown:
    - <<: *prettier
  python:
    - <<: *python-black
  scss:
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  vue:
    - <<: *eslint
    - <<: *prettier
  yaml:
    - <<: *prettier
