version: 2
log-file: "/Users/Oli/.local/state/nvim/efm.log"
log-level: 1
root-markers:
  - .git/
  - package.json

tools:
  eslint: &eslint
    lint-command: "eslint_d -f unix --stdin"
    lint-ignore-exit-code: true
    lint-stdin: true

  google-java-format: &google-java-format
    format-command: "google-java-format -"
    format-stdin: true

  fish: &fish
    format-command: "fish_indent"
    format-stdin: true

  html-prettier: &html-prettier
    format-command: "prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser html"
    format-stdin: true

  isort: &isort
    format-command: "isort --stdout --filename ${INPUT} -"
    format-stdin: true

  php-cs-fixer: &php-cs-fixer
    format-command: "php-cs-fixer fix --quiet"
    format-stdin: true

  prettier: &prettier
    format-command: "prettier --stdin --stdin-filepath ${INPUT} ${--range-start:charStart} ${--range-end:charEnd} ${--tab-width:tabSize} ${--use-tabs:!insertSpaces}"
    format-stdin: true
    format-can-range: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

  python-black: &python-black
    format-command: "black --no-color -q -"
    format-stdin: true

  shfmt: &shfmt
    format-command: "shfmt -filename ${INPUT} -"
    format-stdin: true

  stylua: &stylua
    format-command: "stylua --color Never -"
    format-stdin: true
    root-markers:
      - stylua.toml

languages:
  css:
    - <<: *prettier
  fish:
    - <<: *fish
  html:
    - <<: *html-prettier
  java:
    - <<: *google-java-format
  javascript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  json:
    - <<: *prettier
  lua:
    - <<: *stylua
  markdown:
    - <<: *prettier
  php:
    - <<: *php-cs-fixer
  python:
    - <<: *isort
    - <<: *python-black
  scss:
    - <<: *prettier
  sh:
    - <<: *shfmt
  typescript:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  vue:
    - <<: *eslint
    - <<: *prettier
  yaml:
    - <<: *prettier
