version: 2
log-file: "/Users/Oli/.cache/nvim/efm.log"
log-level: 1
root-markers:
  - .git/
  - package.json
  - yarn.lock
  - requirements.txt
  - Dockerfile
  - README.md
  - .env.dev
  - .env

tools:
  prettier: &prettier
    format-command: "prettier --stdin-filepath ${INPUT}"
    format-stdin: true

  eruby-erb: &eruby-erb
    lint-debounce: 2s
    lint-command: "erb -x -T - | ruby -c"
    lint-stdin: true
    lint-offset: 1
    format-stdin: true
    format-command: htmlbeautifier # Note this is a ruby gem!

  javascript-eslint: &javascript-eslint
    lint-command: "eslint -f visualstudio --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  json-fixjson: &json-fixjson
    format-command: "fixjson"

  lua-lua-format: &lua-lua-format
    format-stdin: true
    format-command: "lua-format -i --single-quote-to-double-quote --no-use-tab --no-keep-simple-control-block-one-line --no-keep-simple-function-one-line --spaces-inside-table-braces --chop-down-table"

  python-black: &python-black
    format-stdin: true
    format-command: "black --quiet -"
  python-isort: &python-isort
    format-stdin: true
    format-command: "isort --quiet -"

  ruby-rubocop: &ruby-rubocop
    format-stdin: true
    format-command: "bundle exec rubocop --format quiet --auto-correct"

  shellcheck-lint: &shellcheck-lint
    prefix: shellcheck
    lint-command: "shellcheck -f gcc -x -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %t%*[^:]: %m [SC%n]"

  shfmt-format: &shfmt-format
    format-command: "shfmt -ln bash -i 2 -bn -ci -sr -kp"
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -d "{extends: relaxed, rules: {line-length: {max: 80}}}" ${INPUT}'
    lint-stdin: true

languages:
  css:
    - <<: *prettier
  dockerfile:
    - <<: *prettier
  eruby:
    - <<: *eruby-erb
  html:
    - <<: *prettier
  javascript:
    - <<: *javascript-eslint
    - <<: *prettier
  json:
    - <<: *json-fixjson
  lua:
    - <<: *lua-lua-format
  python:
    # - <<: *python-flake8
    # - <<: *python-mypy
    # - <<: *python-autopep8
    # - <<: *python-yapf
    - <<: *python-black
    - <<: *python-isort
  # Disable robocop as we use solargraph
  # ruby:
  #   - <<: *ruby-rubocop
  sh:
    - <<: *shellcheck-lint
    # - <<: *shfmt-format
  yaml:
    - <<: *prettier
  vue:
    - <<: *prettier
